name:  testing
run-name: ${{ github.pusher.name }} is learning GitHub Actions

on:  workflow_dispatch 

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: log env var
        env:
          SOME_TEXT: "this is test "
        run: echo "$SOME_TEST"