name:  testing
run-name: ${{ github.actor }} is learning GitHub Actions # 
# github context : https://docs.github.com/en/actions/learn-github-actions/contexts

on:  workflow_dispatch 

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: log env var
        env:
          SOME_TEXT: "this is test "
        run: echo "${SOME_TEST}"